2021-03-14 13:35:13,205 http_request.py[line:66] ERROR: [1/3] HTTPConnectionPool(host='www.clzt.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002507D97C848>, 'Connection to www.clzt.com timed out. (connect timeout=20)'))
2021-03-14 13:35:33,226 http_request.py[line:66] ERROR: [2/3] HTTPConnectionPool(host='www.clzt.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002507D9A4388>, 'Connection to www.clzt.com timed out. (connect timeout=20)'))
2021-03-14 13:35:53,229 http_request.py[line:66] ERROR: [3/3] HTTPConnectionPool(host='www.clzt.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002507D7F9D08>, 'Connection to www.clzt.com timed out. (connect timeout=20)'))
2021-03-14 13:35:53,267 currency.py[line:207] INFO: 'NoneType' object has no attribute 'status_code'===网址错误
2021-03-14 13:35:53,309 currency.py[line:191] INFO: expected string or bytes-like object
2021-03-14 13:35:53,320 currency.py[line:97] INFO: 'NoneType' object has no attribute 'xpath'
2021-03-14 13:35:53,370 currency.py[line:175] INFO: can only concatenate list (not "NoneType") to list
