2021-03-12 20:45:02,751 http_request.py[line:66] ERROR: [1/3] HTTPConnectionPool(host='www.ccteg.cn', port=80): Max retries exceeded with url: /contents/9/25419.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000017E93DF6088>, 'Connection to www.ccteg.cn timed out. (connect timeout=20)'))
